{% set name = "immutabledict" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a6ea13c6baacebdcecb3aed3f1fb571bc3d600777d87518f1d176cc8b207e9c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - immutabledict

about:
  home: https://github.com/corenting/immutabledict
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A fork of frozendict, an immutable wrapper around dictionaries.

extra:
  recipe-maintainers:
    - althonos
